[package]
name = "fotonvoice-inject"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fotonvoice-config = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
arboard = { workspace = true }
notify-rust = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
fotonvoice-winput = { workspace = true }
